# Note: You can use any Debian/Ubuntu based image you want. 
FROM mcr.microsoft.com/devcontainers/base:bullseye

# # Install Python requirements
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends python3-pip \
#     && pip3 install --no-cache-dir -r /tmp/requirements.txt \
#     && rm /tmp/requirements.txt