services:
  # The main application container
  app:
    build:
      context: .  # Build the app image from the current directory
    environment:
      - MODEL_HOST=http://model-runner.docker.internal  # Set environment variable for model host
    network_mode: service:db  # Share network stack with the db service
    restart: "no"  # Do not restart the container automatically
    depends_on:
      - db

  # The PostgreSQL database container
  db:
    image: postgres:latest  # Use the latest official PostgreSQL image
    environment:
      POSTGRES_USER: postgres  # Set the database user
      POSTGRES_PASSWORD: postgres  # Set the database password
      POSTGRES_DB: hackernews_summary  # Set the database name
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist database data in a named volume
    restart: "no"  # Do not restart the container automatically

volumes:
  db_data:
    driver: local  # Use the local driver for the volume
